mineral_catalog/mineral_catalog/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include

from . import views

urlpatterns = [
    path('rocks/', include('rocks.urls')),
    path('admin/', admin.site.urls),
    path('', views.hello_world, name='hello_world'),
]

urlpatterns += staticfiles_urlpatterns()

mineral_catalog/rocks/urls.py
from django.urls import path
from . import views

app_name = 'rocks'

# make our variable, a list, in the old Django, it didn't use to be a list, now it's just a list
urlpatterns = [
    path('', views.rock_list, name='rock_list'),
    path('load-rocks/', views.load_rocks, name='load_rocks'),
    path('<int:pk>/', views.rock_detail, name='rock_detail'),
    path('random/', views.random_rock, name='random_rock'),
    path('<str:letter>/', views.sort_rocks, name='sort_rocks'),
]

mineral_catalog/rocks/models.py
from django.db import models


# Create your models here.
class Rock(models.Model):
    name = models.CharField(max_length=255)
    category = models.TextField(blank=True, default='')
    image_caption = models.TextField(blank=True, default='')
    formula = models.TextField(blank=True, default='')
    strunz_classification = models.TextField(blank=True, default='')
    unit_cell = models.TextField(blank=True, default='')
    color = models.TextField(blank=True, default='')
    crystal_system = models.TextField(blank=True, default='')
    crystal_symmetry = models.TextField(blank=True, default='')
    cleavage = models.TextField(blank=True, default='')
    mohs_scale_hardness = models.TextField(blank=True, default='')
    luster = models.TextField(blank=True, default='')
    streak = models.TextField(blank=True, default='')
    diaphaneity = models.TextField(blank=True, default='')
    optical_properties = models.TextField(blank=True, default='')
    refractive_index = models.TextField(blank=True, default='')
    crystal_habit = models.TextField(blank=True, default='')
    specific_gravity = models.TextField(blank=True, default='')

    def __str__(self):
        return self.name

mineral_catalog/mineral_catalog/views.py
from django.shortcuts import render


def hello_world(request):
    return render(request, 'home.html')

mineral_catalog/rocks/views.py
import json
import random

from django.shortcuts import render, redirect, get_object_or_404

# Create your views here.
from .models import Rock

json_file = 'assets/minerals.json'  # 要指名文件目录


def load_rocks(request):
    Rock.objects.all().delete()         # 每次load rocks之前都要将之前的删除，不然会一直累计

    # open json
    with open(json_file, encoding='utf-8') as f:
        rocks = json.load(f)

    for rock in rocks:
        # create rock object
        Rock.objects.create(         # 从Rock模型中创建一个rock
            name=rock['name'] if 'name' in rock else '',
            category=rock['category'] if 'category' in rock else '',
            image_caption=rock['image caption'] if 'image caption' in rock else '',
            formula=rock['formula'] if 'formula' in rock else '',
            strunz_classification=rock['strunz classification'] if 'strunz classification' in rock else '',
            unit_cell=rock['unit cell'] if 'unit cell' in rock else '',
            color=rock['color'] if 'color' in rock else '',
            crystal_system=rock['cry system'] if 'cry system' in rock else '',
            crystal_symmetry=rock['crystal symmetry'] if 'crystal symmetry' in rock else '',
            cleavage=rock['cleavage'] if 'cleavage' in rock else '',
            mohs_scale_hardness=rock['mohs scale hardness'] if 'mohs scale hardness' in rock else '',
            luster=rock['luster'] if 'luster' in rock else '',
            streak=rock['streak'] if 'streak' in rock else '',
            diaphaneity=rock['diaphaneity'] if 'diaphaneity' in rock else '',
            optical_properties=rock['optical properties'] if 'optical properties' in rock else '',
            refractive_index=rock['refractive index'] if 'refractive index' in rock else '',
            crystal_habit=rock['crystal habit'] if 'crystal habit' in rock else '',
            specific_gravity=rock['specific gravity'] if 'specific gravity' in rock else ''
        )
    return redirect('rocks:rock_list')


def rock_list(request):
    rocks = Rock.objects.all()
    return render(request, 'rocks/rock_list.html', {'rocks': rocks})


def rock_detail(request, pk):
    rock = get_object_or_404(Rock, pk=pk)

    items = []
    for item in rock.items().all():
        for key, value in item:
            key = key.replace('_', ' ').title()
            items.append(key, value)
    rock.items = items

    return render(request, 'rocks/rock_detail.html', {'rock': rock})


def random_rock(request):
    rocks = list(Rock.objects.all())
    rock = random.choice(rocks)
    return render(request, 'rocks/rock_detail.html', {'rock': rock})


def sort_rocks(request, letter):
    rocks_cap = Rock.objects.filter(name__startswith=letter)
    return render(request, 'rocks/rocks_cap.html', {'rocks_cap': rocks_cap})

mineral_catalog/rocks/templates/rocks/rock_detail.html
{% extends 'layout.html' %}
{% load static %}

{% block content %}
<div class="grid-100 mineral__container">
    <h1 class="mineral__name">{{ rock.name }}</h1>
    <div class="mineral__image-bg">
        <img class="mineral__image" src="/static/images/{{ rock.name }}.jpg">
        <p class="mineral__caption">{{ rock.image_caption }}</p>
    </div>
    <div class="mineral__table-container">
        <table class="mineral__table">
            <tbody>
                {% for item in rock.items %}
                    {for key, value in item %}
                        {% if item.value %}
                        <tr>
                            <td class="mineral__category">{{ item.key }}</td>
                            <td>{{ value }}</td>
                        </tr>
                        {% endif %}
                    {% endfor %}
                {% endfor %}
                    
                
<!--                {% if rock.category|length > 0 %}-->
<!--                <tr>-->
<!--                    <td class="mineral__category">Category</td>-->
<!--                    <td>{{ rock.category }}</td>-->
<!--                </tr>-->
<!--                {% endif %}-->
<!--                {% if rock.formula|length > 0 %}-->
<!--                <tr>-->
<!--                    <td class="mineral__category">Formula</td>-->
<!--                    <td>{{ rock.formula }}</td>                    -->
<!--                </tr>-->
<!--                {% endif %}-->
<!--                {% if rock.strunz_classification|length > 0 %}-->
<!--                <tr>-->
<!--                    <td class="mineral__category">Strunz Classification</td>-->
<!--                    <td>{{ rock.strunz_classification }}</td>-->
<!--                </tr>-->
<!--                {% endif %}-->
<!--                {% if rock.color|length > 0 %}-->
<!--                <tr>-->
<!--                    <td class="mineral__category">Color</td>-->
<!--                    <td>{{ rock.color }}</td>-->
<!--                </tr>-->
<!--                {% endif %}-->
<!--                {% if rock.crystal_system|length > 0 %}-->
<!--                <tr>-->
<!--                    <td class="mineral__category">Crystal System</td>-->
<!--                    <td>{{ rock.crystal_system }}</td>-->
<!--                </tr>-->
<!--                {% endif %}-->
<!--                {% if rock.unit_cell|length > 0 %}-->
<!--                <tr>-->
<!--                    <td class="mineral__category">Unit Cell</td>-->
<!--                    <td>{{ rock.unit_cell }}</td>-->
<!--                </tr>-->
<!--                {% endif %}-->
<!--                {% if rock.crystal_symmetry|length > 0 %}-->
<!--                <tr>-->
<!--                    <td class="mineral__category">Crystal Symmetry</td>-->
<!--                    <td>{{ rock.crystal_symmetry }}</td>-->
<!--                </tr>-->
<!--                {% endif %}-->
<!--                {% if rock.cleavage|length > 0 %}-->
<!--                <tr>-->
<!--                    <td class="mineral__category">Cleavage</td>-->
<!--                    <td>{{ rock.cleavage }}</td>-->
<!--                </tr>-->
<!--                {% endif %}-->
<!--                {% if rock.mohs_scale_hardness|length > 0 %}-->
<!--                <tr>-->
<!--                    <td class="mineral__category">Mohs scale Hardness</td>-->
<!--                    <td>{{ rock.mohs_scale_hardness }}</td>-->
<!--                </tr>-->
<!--                {% endif %}-->
<!--                {% if rock.luster|length > 0 %}-->
<!--                <tr>-->
<!--                    <td class="mineral__category">Luster</td>-->
<!--                    <td>{{ rock.luster }}</td>-->
<!--                </tr>-->
<!--                {% endif %}-->
<!--                {% if rock.streak|length > 0 %}-->
<!--                <tr>-->
<!--                    <td class="mineral__category">Streak</td>-->
<!--                    <td>{{ rock.streak }}</td>-->
<!--                </tr>-->
<!--                {% endif %}-->
<!--                {% if rock.diaphaneity|length > 0 %}-->
<!--                <tr>-->
<!--                    <td class="mineral__category">Diaphaneity</td>-->
<!--                    <td>{{ rock.diaphaneity }}</td>-->
<!--                </tr>-->
<!--                {% endif %}-->
<!--                {% if rock.optical_properties|length > 0 %}-->
<!--                <tr>-->
<!--                    <td class="mineral__category">Optical Properties</td>-->
<!--                    <td>{{ rock.optical_properties }}</td>-->
<!--                </tr>-->
<!--                {% endif %}-->
<!--                {% if rock.refractive_index|length > 0 %}-->
<!--                <tr>-->
<!--                    <td class="mineral__category">Refractive Index</td>-->
<!--                    <td>{{ rock.refractive_index }}</td>-->
<!--                </tr>-->
<!--                {% endif %}-->
<!--                {% if rock.crystal_habit|length > 0 %}-->
<!--                <tr>-->
<!--                    <td class="mineral__category">Crystal Habit</td>-->
<!--                    <td>{{ rock.crystal_habit }}</td>-->
<!--                </tr>-->
<!--                {% endif %}-->
<!--                {% if rock.specific_gravity|length > 0 %}-->
<!--                <tr>-->
<!--                    <td class="mineral__category">Specific Gravity</td>-->
<!--                    <td>{{ rock.specific_gravity }}</td>-->
<!--                </tr>-->
<!--                {% endif %}-->
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

mineral_catalog/rocks/templates/rocks/rock_list.html
{% extends 'layout.html' %}

{% block content %}
<div class="grid-100">
    <ul class="minerals__container">
        {% for rock in rocks %}
        <li class="minerals__item">
            <a class="minerals__anchor" href="{% url 'rocks:rock_detail' pk=rock.pk %}">{{ rock.name }}</a>
        </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

mineral_catalog/rocks/templates/rocks/rocks_cap.html
{% extends 'layout.html' %}

{% block content %}
<div class="grid-100">
    <ul class="minerals__container">
        {% for rock in rocks_cap %}
        <li class="minerals__item">
            <a class="minerals__anchor" href="{% url 'rocks:rock_detail' pk=rock.pk %}">{{ rock.name }}</a>
        </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

mineral_catalog/templates/home.html
{% extends 'layout.html' %}

mineral_catalog/templates/layout.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Macky's Mineral: A magnificent catalog of minerals{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/global.css' %}">
</head>
<body>
    <div class="bounds">
        <div class="grid-100">
            <a href="{% url 'rocks:rock_list' %}">
                <h1 class="logo__name text-centered">Macky's Mineral</h1>
            </a>
            <p class="logo__text text-centered">They're not rocks!</p>
        </div>
        <div class="grid-100">
            <table class="letter">
                <tr>
                    {% for letter in 'ABCDEFGHIJKLMNOPQRSTUVWXYZ' %}
                        <td><a href="{% url 'rocks:sort_rocks' letter %}">{{ letter }}</a></td>
                    {% endfor %}
                </tr>
            </table>
        </div>
        {% block content %}{% endblock %}
    </div>
    <div class="minerals__random">
        <a class="minerals__anchor" href="{% url 'rocks:random_rock' %}">Show Random Mineral</a>
        <a class="minerals__anchor" href="{% url 'rocks:load_rocks' %}">Load Rocks</a>
    </div>
</body>
</html>